services:
  app:
    image: ai-stock-predictions:latest
    build: .
    volumes:
      - ai-stock-data:/app/data
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - NODE_ENV=production
      - NODE_OPTIONS=--experimental-transform-types
      - NODE_NO_WARNINGS=1
    stdin_open: true
    tty: true

volumes:
  ai-stock-data:
    name: ai-stock-data
